
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ta' | 'hi' | 'bn' | 'te';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        'app.name': 'Smart Waste',
        'app.subtitle': 'Tamil Nadu 360',
        'nav.dashboard': 'Dashboard',
        'nav.wasteHistory': 'Waste History',
        'nav.statistics': 'Statistics',
        'nav.rewards': 'Rewards',
        'nav.notifications': 'Notifications',
        'nav.myRoute': 'My Route',
        'nav.pickups': 'Pickups',
        'nav.reportIssue': 'Report Issue',
        'nav.attendance': 'Attendance',
        'nav.cityMap': 'City Map',
        'nav.households': 'Households',
        'nav.collectors': 'Collectors',
        'nav.violations': 'Violations',
        'nav.reports': 'Reports',
        'nav.incentives': 'Incentives',
        'nav.stateMap': 'State Map',
        'nav.municipalities': 'Municipalities',
        'nav.policies': 'Policies',
        'nav.wards': 'Wards',
        'nav.staff': 'Staff',
        'nav.fleet': 'Fleet',
        'nav.liveMap': 'Live Map',
        'nav.shifts': 'Shifts',
        'nav.complaints': 'Complaints',
        'nav.tracking': 'Tracking',
        'nav.routes': 'Routes',
        'nav.maintenance': 'Maintenance',
        'nav.centers': 'Centers',
        'nav.inventory': 'Inventory',
        'nav.sales': 'Sales',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',
        'role.household': 'Household',
        'role.collector': 'Waste Collector',
        'role.officer': 'Municipal Officer',
        'common.user': 'User',
        'common.house': 'House',
        'login.title': 'Tamil Nadu Smart Waste 360',
        'login.subtitle': 'Smart Waste Segregation & Recycling System',
        'login.welcome': 'Welcome to',
        'login.brand': 'Smart Waste 360',
        'login.chooseRole': 'Choose your role to access the waste management dashboard. Together, let\'s make Tamil Nadu cleaner and greener.',
        'role.household.title': 'Household User',
        'role.household.desc': 'Access your waste management dashboard, track segregation score, and earn rewards',
        'role.collector.title': 'Waste Collector',
        'role.collector.desc': 'View assigned routes, mark pickups, and report collection status',
        'role.officer.title': 'Municipal Officer',
        'role.officer.desc': 'Monitor city-wide waste management, view analytics, and manage operations',
        'role.third_party.title': '3rd Party Partner',
        'role.third_party.desc': 'View city-wide waste collection data and collaborate with municipal authorities',
        'role.state_admin.title': 'State Admin (CM)',
        'role.state_admin.desc': 'Oversight of entire state waste management and analytics',
        'role.municipal_admin.title': 'Municipal Admin',
        'role.municipal_admin.desc': 'City-level administration and compliance monitoring',
        'role.sanitation.title': 'Sanitation Dept',
        'role.sanitation.desc': 'Manage waste collection operations and bin status',
        'role.logistics.title': 'Logistics Dept',
        'role.logistics.desc': 'Optimize vehicle routes and fleet management',
        'role.recycling.title': 'Recycling Dept',
        'role.recycling.desc': 'Manage processing centers and recycling data',
        'login.button': 'Login',
        'demo.title': 'Demo Credentials',
        'footer.hackathon': 'Smart India Hackathon 2025 | Problem Statement 25046',
        'footer.govt': 'Government of Tamil Nadu - Municipal Administration',
        'language.odia': 'Tamil',
    },
    ta: {
        'app.name': 'ஸ்மார்ட் வேஸ்ட்',
        'app.subtitle': 'தமிழ்நாடு 360',
        'nav.dashboard': 'முகப்பு பலகை',
        'nav.wasteHistory': 'கழிவு வரலாறு',
        'nav.statistics': 'புள்ளிவிவரங்கள்',
        'nav.rewards': 'வெகுமதிகள்',
        'nav.notifications': 'அறிவிப்புகள்',
        'nav.myRoute': 'எனது பாதை',
        'nav.pickups': 'சேகரிப்புகள்',
        'nav.reportIssue': 'புகார் அளிக்கவும்',
        'nav.attendance': 'வருகை',
        'nav.cityMap': 'நகர வரைபடம்',
        'nav.households': 'குடும்பங்கள்',
        'nav.collectors': 'சேகரிப்பாளர்கள்',
        'nav.violations': 'மீறல்கள்',
        'nav.reports': 'அறிக்கைகள்',
        'nav.incentives': 'ஊக்கத்தொகைகள்',
        'nav.settings': 'அமைப்புகள்',
        'nav.logout': 'வெளியேறு',
        'role.household': 'குடும்பம்',
        'role.collector': 'கழிவு சேகரிப்பாளர்',
        'role.officer': 'நகராட்சி அதிகாரி',
        'role.third_party': 'மூன்றாம் தரப்பு',
        'common.user': 'பயனர்',
        'common.house': 'வீடு',
        'login.title': 'தமிழ்நாடு ஸ்மார்ட் வேஸ்ட் 360',
        'login.subtitle': 'ஸ்மார்ட் கழிவு பிரிப்பு மற்றும் மறுசுழற்சி அமைப்பு',
        'login.welcome': 'நல்வரவு',
        'login.brand': 'ஸ்மார்ட் வேஸ்ட் 360',
        'login.chooseRole': 'கழிவு மேலாண்மை பலகையை அணுக உங்கள் பாத்திரத்தைத் தேர்வுசெய்யவும். ஒன்றாக இணைந்து தமிழ்நாட்டைத் தூய்மையாகவும் பசுமையாகவும் மாற்றுவோம்.',
        'role.household.title': 'குடும்ப பயனர்',
        'role.household.desc': 'உங்கள் கழிவு மேலாண்மை பலகையை அணுகவும், பிரிப்பு மதிப்பெண்ணைக் கண்காணிக்கவும் மற்றும் வெகுமதிகளைப் பெறவும்',
        'role.collector.title': 'கழிவு சேகரிப்பாளர்',
        'role.collector.desc': 'ஒதுக்கப்பட்ட பாதைகளைப் பார்க்கவும், சேகரிப்புகளைக் குறிக்கவும் மற்றும் நிலையைத் தெரிவிக்கவும்',
        'role.officer.title': 'நகராட்சி அதிகாரி',
        'role.officer.desc': 'நகரம் தழுவிய கழிவு மேலாண்மையைக் கண்காணிக்கவும், பகுப்பாய்வுகளைப் பார்க்கவும் மற்றும் செயல்பாடுகளை நிர்வகிக்கவும்',
        'role.third_party.title': 'மூன்றாம் தரப்பு கூட்டாளர்',
        'role.third_party.desc': 'நகரம் தழுவிய கழிவு சேகரிப்பு தரவைப் பார்க்கவும் மற்றும் நகராட்சி அதிகாரிகளுடன் ஒத்துழைக்கவும்',
        'role.state_admin.title': 'மாநில நிர்வாகி (CM)',
        'role.state_admin.desc': 'முழு மாநில கழிவு மேலாண்மை மற்றும் பகுப்பாய்வுகளின் மேற்பார்வை',
        'role.municipal_admin.title': 'நகராட்சி நிர்வாகி',
        'role.municipal_admin.desc': 'நகர அளவிலான நிர்வாகம் மற்றும் இணக்கக் கண்காணிப்பு',
        'role.sanitation.title': 'சுகாதாரத் துறை',
        'role.sanitation.desc': 'கழிவு சேகரிப்பு செயல்பாடுகள் மற்றும் பின்களின் நிலையை நிர்வகிக்கவும்',
        'role.logistics.title': 'தளவாடத் துறை',
        'role.logistics.desc': 'வாகனப் பாதைகள் மற்றும் கடற்படை மேலாண்மையை மேம்படுத்தவும்',
        'role.recycling.title': 'மறுசுழற்சித் துறை',
        'role.recycling.desc': 'செயலாக்க மையங்கள் மற்றும் மறுசுழற்சி தரவுகளை நிர்வகிக்கவும்',
        'login.button': 'உள்நுழைய',
        'demo.title': 'முன்னோட்ட சான்றுகள்',
        'footer.hackathon': 'ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2025 | சிக்கல் அறிக்கை 25046',
        'footer.govt': 'தமிழ்நாடு அரசு - நகராட்சி நிர்வாகம்',
        'language.odia': 'தமிழ்',
    },
    hi: {
        'app.name': 'स्मार्ट वेस्ट',
        'app.subtitle': 'तमिलनाडु 360',
        'nav.dashboard': 'डैशबोर्ड',
        'nav.wasteHistory': 'कचरा इतिहास',
        'nav.statistics': 'आंकड़े',
        'nav.rewards': 'पुरस्कार',
        'nav.notifications': 'सूचनाएं',
        'nav.myRoute': 'मेरा मार्ग',
        'nav.pickups': 'पिकअप',
        'nav.reportIssue': 'समस्या रिपोर्ट करें',
        'nav.attendance': 'उपस्थिति',
        'nav.cityMap': 'शहर का नक्शा',
        'nav.households': 'परिवार',
        'nav.collectors': 'संग्रहकर्ता',
        'nav.violations': 'उल्लंघन',
        'nav.reports': 'रिपोर्ट',
        'nav.incentives': 'प्रोत्साहन',
        'nav.settings': 'सेटिंग्स',
        'nav.logout': 'लॉग आउट',
        'role.household': 'घरेलू',
        'role.collector': 'कचरा संग्रहकर्ता',
        'role.officer': 'नगर अधिकारी',
        'role.third_party': 'तीसरा पक्ष',
        'common.user': 'उपयोगकर्ता',
        'common.house': 'घर',
        'login.title': 'तमिलनाडु स्मार्ट वेस्ट 360',
        'login.subtitle': 'स्मार्ट कचरा पृथक्करण और पुनर्चक्रण प्रणाली',
        'login.welcome': 'स्वागत है',
        'login.brand': 'स्मार्ट वेस्ट 360',
        'login.chooseRole': 'कचरा प्रबंधन डैशबोर्ड तक पहुंचने के लिए अपनी भूमिका चुनें। आइए मिलकर तमिलनाडु को स्वच्छ और हरा-भरा बनाएं।',
        'role.household.title': 'घरेलू उपयोगकर्ता',
        'role.household.desc': 'अपने कचरा प्रबंधन डैशबोर्ड तक पहुंचें, पृथक्करण स्कोर ट्रैक करें और पुरस्कार अर्जित करें',
        'role.collector.title': 'कचरा संग्रहकर्ता',
        'role.collector.desc': 'निर्दिष्ट मार्ग देखें, पिकअप चिह्नित करें और संग्रह स्थिति रिपोर्ट करें',
        'role.officer.title': 'नगर अधिकारी',
        'role.officer.desc': 'शहर-व्यापी कचरा प्रबंधन की निगरानी करें, विश्लेषण देखें और संचालन का प्रबंधन करें',
        'role.third_party.title': 'तीसरा पक्ष भागीदार',
        'role.third_party.desc': 'शहर-व्यापी कचरा संग्रह डेटा देखें और नगरपालिका अधिकारियों के साथ सहयोग करें',
        'role.state_admin.title': 'राज्य प्रशासक (सीएम)',
        'role.state_admin.desc': 'पूरे राज्य के कचरा प्रबंधन और विश्लेषण की निगरानी',
        'role.municipal_admin.title': 'नगरपालिका प्रशासक',
        'role.municipal_admin.desc': 'शहर स्तर का प्रशासन और अनुपालन निगरानी',
        'role.sanitation.title': 'स्वच्छता विभाग',
        'role.sanitation.desc': 'कचरा संग्रह संचालन और बिन स्थिति का प्रबंधन करें',
        'role.logistics.title': 'रसद विभाग',
        'role.logistics.desc': 'वाहन मार्गों और बेड़े प्रबंधन का अनुकूलन करें',
        'role.recycling.title': 'पुनर्चक्रण विभाग',
        'role.recycling.desc': 'प्रसंस्करण केंद्रों और पुनर्चक्रण डेटा का प्रबंधन करें',
        'login.button': 'लॉग इन करें',
        'demo.title': 'डेमो क्रेडेंशियल्स',
        'footer.hackathon': 'स्मार्ट इंडिया हैकाथॉन 2025 | समस्या विवरण 25046',
        'footer.govt': 'तमिलनाडु सरकार - नगरपालिका प्रशासन',
        'language.odia': 'ओड़िया',
    },
    bn: {
        'app.name': 'স্মার্ট ওয়েস্ট',
        'app.subtitle': 'তামিলনাড়ু ৩৬০',
        'nav.dashboard': 'ড্যাশবোর্ড',
        'nav.wasteHistory': 'বর্জ্য ইতিহাস',
        'nav.statistics': 'পরিসংখ্যান',
        'nav.rewards': 'পুরস্কার',
        'nav.notifications': 'বিজ্ঞপ্তি',
        'nav.myRoute': 'আমার রুট',
        'nav.pickups': 'পিকআপ',
        'nav.reportIssue': 'সমস্যা রিপোর্ট করুন',
        'nav.attendance': 'উপস্থিতি',
        'nav.cityMap': 'শহরের মানচিত্র',
        'nav.households': 'পরিবার',
        'nav.collectors': 'সংগ্রহকারী',
        'nav.violations': 'লঙ্ঘন',
        'nav.reports': 'রিপোর্ট',
        'nav.incentives': 'প্রোৎসাহন',
        'nav.settings': 'সেটিংস',
        'nav.logout': 'লগআউট',
        'role.household': 'পরিবার',
        'role.collector': 'বর্জ্য সংগ্রহকারী',
        'role.officer': 'পৌর কর্মকর্তা',
        'role.third_party': 'তৃতীয় পক্ষ',
        'common.user': 'ব্যবহারকারী',
        'common.house': 'ঘর',
        'login.title': 'তামিলনাড়ু স্মার্ট ওয়েস্ট ৩৬০',
        'login.subtitle': 'স্মার্ট বর্জ্য পৃথকীকরণ এবং পুনর্ব্যবহারযোগ্য ব্যবস্থা',
        'login.welcome': 'স্বাগতম',
        'login.brand': 'স্মার্ট ওয়েস্ট ৩৬০',
        'login.chooseRole': 'বর্জ্য ব্যবস্থাপনা ড্যাশবোর্ড অ্যাক্সেস করতে আপনার ভূমিকা চয়ন করুন। আসুন একসাথে তামিলনাড়ুকে পরিষ্কার এবং সবুজ করে তুলি।',
        'role.household.title': 'পারিবারিক ব্যবহারকারী',
        'role.household.desc': 'আপনার বর্জ্য ব্যবস্থাপনা ড্যাশবোর্ড অ্যাক্সেস করুন, পৃথকীকরণ স্কোর ট্র্যাক করুন এবং পুরস্কার অর্জন করুন',
        'role.collector.title': 'বর্জ্য সংগ্রহকারী',
        'role.collector.desc': 'অর্পিত রুট দেখুন, পিকআপ চিহ্নিত করুন এবং সংগ্রহের স্থিতি রিপোর্ট করুন',
        'role.officer.title': 'পৌর কর্মকর্তা',
        'role.officer.desc': 'শহরব্যাপী বর্জ্য ব্যবস্থাপনা পর্যবেক্ষণ করুন, বিশ্লেষণ দেখুন এবং ক্রিয়াকলাপ পরিচালনা করুন',
        'role.third_party.title': 'তৃতীয় পক্ষ অংশীদার',
        'role.third_party.desc': 'শহরব্যাপী বর্জ্য সংগ্রহ ডেটা দেখুন এবং পৌর কর্তৃপক্ষের সাথে সহযোগিতা করুন',
        'role.state_admin.title': 'রাজ্য প্রশাসক (সিএম)',
        'role.state_admin.desc': 'সমগ্র রাজ্যের বর্জ্য ব্যবস্থাপনা এবং বিশ্লেষণের তদারকি',
        'role.municipal_admin.title': 'পৌর প্রশাসক',
        'role.municipal_admin.desc': 'শহর স্তরের প্রশাসন এবং সম্মতি পর্যবেক্ষণ',
        'role.sanitation.title': 'স্যানিটেশন বিভাগ',
        'role.sanitation.desc': 'বর্জ্য সংগ্রহ অপারেশন এবং বিন স্থিতি পরিচালনা করুন',
        'role.logistics.title': 'লজিস্টিক বিভাগ',
        'role.logistics.desc': 'যানবাহনের রুট এবং ফ্লিট ম্যানেজমেন্ট অপ্টিমাইজ করুন',
        'role.recycling.title': 'রিসাইক্লিং বিভাগ',
        'role.recycling.desc': 'প্রসেসিং কেন্দ্র এবং রিসাইক্লিং ডেটা পরিচালনা করুন',
        'login.button': 'লগইন',
        'demo.title': 'ডেমো ক্রেডেনশিয়াল',
        'footer.hackathon': 'স্মার্ট ইন্ডিয়া হ্যাকাথন ২০২৫ | সমস্যা বিবৃতি ২৫০৪৬',
        'footer.govt': 'তামিলনাড়ু সরকার - পৌর প্রশাসন',
        'language.odia': 'তামিল',
    },
    te: {
        'app.name': 'స్మార్ట్ వేస్ట్',
        'app.subtitle': 'తమిళనాడు 360',
        'nav.dashboard': 'డ్యాష్‌బోర్డ్',
        'nav.wasteHistory': 'చెత్త చరిత్ర',
        'nav.statistics': 'గణాంకాలు',
        'nav.rewards': 'బహుమతులు',
        'nav.notifications': 'నోటిఫికేషన్‌లు',
        'nav.myRoute': 'నా రూట్',
        'nav.pickups': 'పికప్‌లు',
        'nav.reportIssue': 'సమస్యను నివేదించండి',
        'nav.attendance': 'హాజరు',
        'nav.cityMap': 'నగర పటం',
        'nav.households': 'కుటుంబాలు',
        'nav.collectors': 'సేకరణకర్తలు',
        'nav.violations': 'ఉల్లంఘనలు',
        'nav.reports': 'నివేదికలు',
        'nav.incentives': 'ప్రోత్సాహకాలు',
        'nav.settings': 'సెట్టింగ్‌లు',
        'nav.logout': 'లాగ్ అవుట్',
        'role.household': 'కుటుంబం',
        'role.collector': 'చెత్త సేకరణకర్త',
        'role.officer': 'మున్సిపల్ ఆఫీసర్',
        'role.third_party': 'థర్డ్ పార్టీ',
        'common.user': 'వినియోగదారు',
        'common.house': 'ఇల్లు',
        'login.title': 'తమిళనాడు స్మార్ట్ వేస్ట్ 360',
        'login.subtitle': 'స్మార్ట్ చెత్త విభజన మరియు రీసైక్లింగ్ వ్యవస్థ',
        'login.welcome': 'స్వాగతం',
        'login.brand': 'స్మార్ట్ వేస్ట్ 360',
        'login.chooseRole': 'చెత్త నిర్వహణ డ్యాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి మీ పాత్రను ఎంచుకోండి. తమిళనాడును స్వచ్ఛంగా మరియు పచ్చగా మార్చడానికి కలిసి పనిచేద్దాం.',
        'role.household.title': 'కుటుంబ వినియోగదారు',
        'role.household.desc': 'మీ చెత్త నిర్వహణ డ్యాష్‌బోర్డ్‌ను యాక్సెస్ చేయండి, విభజన స్కోర్‌ను ట్రాక్ చేయండి మరియు బహుమతులు పొందండి',
        'role.collector.title': 'చెత్త సేకరణకర్త',
        'role.collector.desc': 'కేటాయించిన రూట్‌లను చూడండి, పికప్‌లను గుర్తించండి మరియు సేకరణ స్థితిని నివేదించండి',
        'role.officer.title': 'మున్సిపల్ ఆఫీసర్',
        'role.officer.desc': 'నగర వ్యాప్తంగా చెత్త నిర్వహణను పర్యవేక్షించండి, విశ్లేషణలను చూడండి మరియు కార్యకలాపాలను నిర్వహించండి',
        'role.third_party.title': 'థర్డ్ పార్టీ భాగస్వామి',
        'role.third_party.desc': 'నగర వ్యాప్తంగా చెత్త సేకరణ డేటాను చూడండి మరియు మున్సిపల్ అధికారులతో సహకరించండి',
        'role.state_admin.title': 'రాష్ట్ర అడ్మినిస్ట్రేటర్ (CM)',
        'role.state_admin.desc': 'మొత్తం రాష్ట్ర చెత్త నిర్వహణ మరియు విశ్లేషణల పర్యవేక్షణ',
        'role.municipal_admin.title': 'మున్సిపల్ అడ్మినిస్ట్రేటర్',
        'role.municipal_admin.desc': 'నగర స్థాయి పరిపాలన మరియు నిబంధనల పర్యవేక్షణ',
        'role.sanitation.title': 'పారిశుద్ధ్య విభాగం',
        'role.sanitation.desc': 'చెత్త సేకరణ కార్యకలాపాలు మరియు బిన్ స్థితిని నిర్వహించండి',
        'role.logistics.title': 'లాజిస్టిక్స్ విభాగం',
        'role.logistics.desc': 'వాహన రూట్‌లు మరియు ఫ్లీట్ నిర్వహణను ఆప్టిమైజ్ చేయండి',
        'role.recycling.title': 'రీసైక్లింగ్ విభాగం',
        'role.recycling.desc': 'ప్రాసెసింగ్ కేంద్రాలు మరియు రీసైక్లింగ్ డేటాను నిర్వహించండి',
        'login.button': 'లాగిన్',
        'demo.title': 'డెమో క్రెడెన్షియల్స్',
        'footer.hackathon': 'స్మార్ట్ ఇండియా హ్యాకథాన్ 2025 | సమస్య ప్రకటన 25046',
        'footer.govt': 'తమిళనాడు ప్రభుత్వం - మున్సిపల్ పరిపాలన',
        'language.odia': 'తమిళం',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    // Load language from local storage on mount
    useEffect(() => {
        const savedLang = localStorage.getItem('app-language') as Language;
        if (savedLang && ['en', 'ta', 'hi', 'bn', 'te'].includes(savedLang)) {
            setLanguage(savedLang);
        }
    }, []);

    // Save language to local storage when changed
    useEffect(() => {
        localStorage.setItem('app-language', language);
    }, [language]);

    const t = (key: string): string => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
